name = "BipartiteGraphs"
uuid = "caf10ac8-0290-4205-88aa-f15908547e8d"
authors = ["Aayush Sabharwal <aayush.sabharwal@gmail.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"

[weakdeps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[extensions]
BipartiteGraphsSparseArraysExt = "SparseArrays"

[compat]
DocStringExtensions = "0.7, 0.8, 0.9"
Graphs = "1.5.2"
SparseArrays = "1"
julia = "1.10"
