name = "BipartiteGraphs"
uuid = "caf10ac8-0290-4205-88aa-f15908547e8d"
authors = ["Aayush Sabharwal <aayush.sabharwal@gmail.com>"]
version = "0.1.6"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[weakdeps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[extensions]
BipartiteGraphsSparseArraysExt = "SparseArrays"

[compat]
DataStructures = "0.18, 0.19"
DocStringExtensions = "0.8, 0.9"
Graphs = "1.9"
PrecompileTools = "1"
SparseArrays = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
