[deps]
BipartiteGraphs = "caf10ac8-0290-4205-88aa-f15908547e8d"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"

[compat]
BipartiteGraphs = "0.1"
Documenter = "1"
Graphs = "1"
